#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp

yabai -m config window_origin_display default
yabai -m config window_placement second_child

yabai -m config auto_balance on

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config window_shadow float

yabai -m config top_padding 6
yabai -m config bottom_padding 6
yabai -m config left_padding 6
yabai -m config right_padding 6
yabai -m config window_gap 6

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add app="^Arc$" manage=on

yabai -m rule --apply

borders active_color=0xff7cfc00 inactive_color=0xff708090 width=6.0 &
