# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = 'zsh'

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins]

[plugins.starship]
inline = 'eval "$(starship init zsh)"'
 
[plugins.mise]
inline = 'eval "$(mise activate --shims)"'
 
[plugins.zsh-defer]
github = 'romkatv/zsh-defer'
 
[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{completion,key-bindings,directories}.zsh"]
hooks.pre = 'autoload -Uz compinit && compinit'
apply = ['defer']
 
[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']
 
[plugins.zsh-abbr]
github = 'olets/zsh-abbr'
hooks.post = 'zsh-defer source $HOME/.config/sheldon/zsh/abbr.post.zsh'
apply = ['defer']
 
[plugins.fzf]
inline = 'zsh-defer source $HOME/.config/sheldon/zsh/fzf.post.zsh'

[plugins.gh]
inline = 'zsh-defer eval "$(gh completion -s zsh)"'
